language: python
dist: xenial
sudo: required
addons:
  postgresql: "10"
  apt:
    packages:
      - libyajl-dev  # for jsonslicer python module
      - postgresql-server-dev-10  # for postgresql-libversion
      #- python3-rpm  # stock package is python3.5, useless for us
      - libnss3-dev  # for rpm
      - libnspr4-dev  # for rpm
      - libmagic-dev  # for rpm
      - libpopt-dev  # for rpm
      - libarchive-dev  # for rpm
      - libdb5.3-dev  # for rpm
env:
  global:
    - REPOLOGY_CONFIG=repology-test.conf.default
cache: pip
matrix:
  include:
    - python: 3.7
      env: COVERAGE=yes
    - python: 3.8-dev
    - python: nightly
  allow_failures:  # werkzeug incompatibility
    - python: 3.8-dev
    - python: nightly
before_install:
  - export REAL_PYTHON=$(basename $(dirname $(python-config --configdir)))
  - |-
    mkdir -p dep-rpm
    (
        cd dep-rpm &&
        wget -qO- http://ftp.rpm.org/releases/rpm-4.14.x/rpm-4.14.2.1.tar.bz2 | tar -x -j -f- --strip-components 1 &&
        env PYTHON_CFLAGS="$(python-config --cflags)" PYTHON_LIBS="-L$(python-config --configdir) $(python-config --ldflags)" ./configure --enable-python --without-lua &&
        make &&
        sudo make install &&
        cp -Rfv "/usr/local/lib/${REAL_PYTHON}/site-packages/rpm" "${VIRTUAL_ENV}/lib/${REAL_PYTHON}/site-packages/"
    )
  - |-
    mkdir -p dep-libversion
    (
        cd dep-libversion &&
        wget -qO- https://github.com/repology/libversion/archive/master.tar.gz | tar -x -z -f- --strip-components 1 &&
        cmake . &&
        make &&
        sudo make install &&
        sudo ldconfig
    )
  - |-
    mkdir -p dep-postgresql-libversion
    (
        cd dep-postgresql-libversion &&
        wget -qO- https://github.com/repology/postgresql-libversion/archive/master.tar.gz | tar -x -z -f- --strip-components 1 &&
        make &&
        sudo make install
    )

  # install mandatory python dependencies
  - pip install Jinja2
  - pip install PyYAML
  - pip install jsonslicer
  - pip install libversion
  - pip install lxml
  - pip install psycopg2
  - pip install pyparsing
  - pip install requests
  - pip install rubymarshal
  - pip install protobuf

  # install extra python dependencies
  - pip install codecov
  - pip install coveralls
  - pip install flake8
  - pip install flake8-builtins!=1.1.0
  - pip install flake8-import-order
  - pip install flake8-quotes
  - pip install mypy>=0.720
  - pip install voluptuous

  # get rules
  - git clone --depth=1 https://github.com/repology/repology-rules.git rules.d
before_script:
  - sudo -u postgres psql -c "CREATE DATABASE repology_test;"
  - sudo -u postgres psql -c "CREATE USER repology_test WITH PASSWORD 'repology_test'"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE repology_test TO repology_test"
  - sudo -u postgres psql -d repology_test -c "CREATE EXTENSION IF NOT EXISTS pg_trgm"
  - sudo -u postgres psql -d repology_test -c "CREATE EXTENSION IF NOT EXISTS libversion"
script:
  # check yaml schemas
  - make check

  # check python syntax
  - make flake8

  # check python types
  - make mypy

  # fill database with test data
  - ./repology-update.py --initdb --parse --database --postupdate

  # smoke test bits
  - ./repology-dump.py --help
  - ./repology-gensitemap.py --main > sitemap-main.xml
  - ./repology-gensitemap.py --metapackages > sitemap-metapackages.xml

  # run unit tests with coverage
  - coverage run --source=repology --omit="repology/test/*,repology/fetchers/*" -m unittest discover

after_success:
  - if [ -n "$COVERAGE" ]; then coveralls; codecov; fi
